#!/usr/bin/env bash

set -e

CNAME="agileavatars.com"
DOCS="docs"

rm -rf "$DOCS"
mkdir -p "$DOCS"
tar -xzvf "agileavatars.tar.gz" -C "$DOCS/"
echo $CNAME >> $DOCS/CNAME
echo $(date -u +"%Y%m%dT%H%M%SZ") >> $DOCS/TIMESTAMP

(
    git add $DOCS
    git commit -m 'Automated deployment'
    git push -u origin master
)

