#!/usr/bin/env bash

set -e

CNAME="agileavatars.com"
DOCS="docs"

rm -rf "$DOCS"
mkdir -p "$DOCS"
tar -xzvf "agileavatars.tar.gz" -C "$DOCS/"
echo $CNAME >> $DOCS/CNAME

(
    git add $DOCS
    git diff --quiet && git diff --staged --quiet || git commit -am 'Automated deployment'    
    git push
)
